### ISSUE TITLE
Configure tab to cycle through options

### ISSUE THREAD

**Issue by tsjnsn** [bonnefoa/kubectl-fzf#11]
I didnt see where this is configurable, but it would be nice to have similar or configurable semantics as zsh's normal completion
1. tab to cycle through options
2. space to accept

**Comment by bonnefoa** [comment]
You can configure binding through the KUBECTL_FZF_OPTIONS environment variable.
I've added an example in https://github.com/bonnefoa/kubectl-fzf#options

There's no cycle action but you could do something like:
```
export KUBECTL_FZF_OPTIONS=(-1 --header-lines=2 --layout reverse -e --no-hscroll --no-sort --bind space:accept --bind tab:down)
```
