### ISSUE TITLE
unexpected date error after pressing "kubectl get pod tab".

### ISSUE THREAD

**Issue by lks21c** [bonnefoa/kubectl-fzf#15]
Hi, I'm so interested in your work, and tried to apply on my Mac.

But I got error below and took around 10 secs to see fzf-preview. could you help me out?

![image](https://user-images.githubusercontent.com/3079144/68528050-67ebaa00-0331-11ea-80e1-e7c8319af5ba.png)

**Comment by bonnefoa** [comment]
Hi,

I'm using `date -r` which is not available in date provided by MacOs.
You can fix the issue by installing https://formulae.brew.sh/formula/coreutils (with `brew install coreutils`). 
I've added it to the list of requirements.

**Comment by dkadio** [comment]
Hi, 

same issue here. But installing coreutils doesn't fix it for me. date -r 123 prints out "Do  1 Jan 1970 01:02:03 CET", so seems to be working. Any idea?

**Comment by j33ty** [comment]
`-r` option is available in `date` binary of MacOS, it just needs `date -r "$file" +%s` instead of `date +%s -r "$file"`.
Raised a PR to fix this, I hope this doesn't break `date` for other OSes.
