### ISSUE TITLE
SSH/Rsync error on tabbing the pods

### ISSUE THREAD

**Issue by vakker** [bonnefoa/kubectl-fzf#17]
When I type `kubectl get <tab>` it shows me the right list of resources, I select pods and tab again for the exact pods when I get:
```
ssh: Could not resolve hostname rsync: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.2]
```

But the process does succeed, I get the right pod name and everything works, except there's that error message. I.e. after selecting the pod name I end up with:
```
$ kubectl get pods ssh: Could not resolve hostname rsync: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.2]
 argo-ui-5799bcf744-l8hqb -n argo 
NAME                       READY   STATUS        RESTARTS   AGE
argo-ui-5799bcf744-l8hqb   1/1     Terminating   0          9d
```
Same happens for other resources as well.

I'm on Ubuntu, using Zsh with Zplug and locally running `cache_builder`.

**Comment by bonnefoa** [comment]
The autocompletion check if there's a `kubectl-fzf` pod running and rsync from it.

Can you check if you don't have a pod running with `kubectl get endpoints -l app=kubectl-fzf --all-namespaces`?
What's the value of `cat $KUBECTL_FZF_CACHE/$(kubectl config current-context)_cache_endpoint`?

**Comment by vakker** [comment]
Thanks for the reply.
I don't have a pod running, I followed the [local version](https://github.com/bonnefoa/kubectl-fzf#cache_builder-local-version) instructions that just writes the cache locally.

**Comment by odelucca** [comment]
Hi @bonnefoa, same thing happening here. I've installed the local version too.

The output of `cat $KUBECTL_FZF_CACHE/$(kubectl config current-context)_cache_endpoint` is `No services found`

**Comment by bonnefoa** [comment]
Should be fixed with https://github.com/bonnefoa/kubectl-fzf/commit/f2a66fdf69f1551cec8b1ae7d048e27449a2fc64

**Comment by bonnefoa** [comment]
kubectl-fzf is not using rsync anymore, closing it.
