### ISSUE TITLE
bash: nouns: bad array subscript

### ISSUE THREAD

**Issue by fvigotti** [bonnefoa/kubectl-fzf#20]
pressed <tab> after "get" , 
```sh
k -n kube-system get bash: nouns: bad array subscript


Warning: Program '/bin/bash' crashed.
```

if I press the tab after "-n" works correctly,
so sometimes works sometimes not.. but when the error is returned the whole shell instance crashes which is very very bad ( I have to  reopen console )

the problem is maybe here : 
https://github.com/bonnefoa/kubectl-fzf/blob/master/kubectl_fzf.sh#L529
but I'm not expert enough in bash to fix it

**Comment by fvigotti** [comment]
replace the line with : 
```sh
[ -n "$nouns" ] && __kubectl_parse_get "${nouns[${#nouns[@]} -1]}"
```
could be a "workaround" but I'm sure you can come up with something better :)

**Comment by bonnefoa** [comment]
Flag parsing has been completely reworked in v3. This shouldn't happen anymore.
