### ISSUE TITLE
Any idea why kubectl autocompletion a random alias?

### ISSUE THREAD

**Issue by rlejeune** [bonnefoa/kubectl-fzf#25]
I know the problem is on my side, but I cannot figure out why.

When I type `kubectl <TAB>` the aucompletion will offer me the list of every command I can use. If I choose any of them and TAB again then it'll just start NPM in my terminal. If I have a package.json present it'll start `npm run test`. If not then I have a `error code ENOENT`. 

If I remove my `test` alias, which calls `npm run test` then it calls something else. 

Thanks in advance if by any chance you could help me with that :)

**Comment by bonnefoa** [comment]
The completion system has been completely rewrote and I was able to remove a considerable amount of shell hack.
You should not encounter this anymore.
Thanks!
