### ISSUE TITLE
Completition tries to cut file that doesnt exists

### ISSUE THREAD

**Issue by dkadio** [bonnefoa/kubectl-fzf#26]
Hi there, 

just installed the cache_builder. Works great, files are written to standard tmp directory. 
After sourcing completion for zsh i get an empty output:
![Screenshot from 2020-11-13 18-57-35](https://user-images.githubusercontent.com/5947518/99105171-555e1d80-25e2-11eb-9aae-d381946dd216.png)

If a interupt Ive get following msg:
cut: /tmp/kubectl_fzf_cache/xx/pods_resource: No such file or directory

Do you know whats wrong here and why cache builder isnt createing this file?

**Comment by on99** [comment]
I'm encountering the same issue.

**Comment by BirkhoffLee** [comment]
Same here on macOS

**Comment by aweis89** [comment]
On mac os as well:
```
cut: /tmp/kubectl_fzf_cache/.../pods_resource: No such file or directory
cut: /tmp/kubectl_fzf_cache/.../pods_resource: No such file or directory
```

**Comment by bonnefoa** [comment]
This should be fixed with the latest release.
There was a mismatch between the released binary and the autocompletion script.

**Comment by dkadio** [comment]
Nice! Thank you man! I really enjoy this tool.
