### ISSUE TITLE
Unauthorized error even after login

### ISSUE THREAD

**Issue by coulof** [bonnefoa/kubectl-fzf#28]
Hi,
I have a local cache_builder started as a daemon. To access most of my clusters I have to login.

The problem is that cache_builder returns Unauthorized errors until I restart it :
```
E0201 08:48:53.598442    1067 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: Unauthorized
```

Would it be possible to support "hot" client refresh ?

Thanks !

**Comment by bonnefoa** [comment]
I've added the option to `--exit-on-unauthorized` to the `kubectl-fzf-server`
Coupled with a systemd unit, you should be able to automatically restart.
