### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by ghostbuster91** [bonnefoa/kubectl-fzf#3]
Hi, great project!

My fzf completion for k8 resources shows empty list and once I quit it, it displays following error:
```
kubectl get pods awk: cannot open /tmp/kubectl_fzf_cache/my-cluster/pods_header (No such file or directory)
cat: /tmp/kubectl_fzf_cache/my-cluster/pods_header: No such file or directory
cut: invalid field range
Try 'cut --help' for more information.
cat: /tmp/kubectl_fzf_cache/my-cluster/pods: No such file or directory
cut: invalid field range
Try 'cut --help' for more information.
kubectl
```
I think that it might be connected with the error I get when running `cache_builder` separately:
```
cache_builder
Fatal error: No Auth Provider found for name "gcp"
```

Any ideas how to fix that?

Edit: I found that @eekwong did some adjustments for gcp and it worked also for me. 
Here is the commit: https://github.com/eekwong/kubectl-fzf/commit/18b3ff015652e8618a2de7442154504688e1c064

It looks more like a workaround than final solution but maybe you could incorporate it somehow.

**Comment by bonnefoa** [comment]
I've pushed gke support on master, you can try updating with 

```
go get github.com/bonnefoa/kubectl-fzf/cmd/cache_builder
```

eekwong's method of getting the rawConfig seems to be the only way to get the context.
