### ISSUE TITLE
zsh broken with kubectl 1.22

### ISSUE THREAD

**Issue by bchess** [bonnefoa/kubectl-fzf#31]
kubectl 1.22 made major changes to zsh autocompletion https://github.com/kubernetes/kubernetes/commit/77bb053102cbe1581857dd35e9c095888d2c85d3

kubectl-fzf no longer works with this

**Comment by ghostbuster91** [comment]
I've just discovered that if you do `source <(kubectl completion zsh)` then standard auto-completion from fzf-tab works! It is not as good as kubectl-fzf since it only shows objects names without other metadata like namespace etc but it works, and will continue working.

**Comment by ghostbuster91** [comment]
Unfortunately it seems so :(

**Comment by bonnefoa** [comment]
Hey, author here! 

The `kubectl` update required a good amount of rewrite and design changes.
I've finally managed to get some time to tackle those and released the v3.
It's still a pre-release and I'm still chasing down the bugs and updating the readme but the base functions should work.

Happy to get any issues and bugs you encounter with the v3!

**Comment by bchess** [comment]
Amazing! I will check it out. Thank you!
