### ISSUE TITLE
kubectl_fzf.sh is missing in the master

### ISSUE THREAD

**Issue by marckamerbeek** [bonnefoa/kubectl-fzf#34]
Hi, 

Followed the readme, but kubectl_fzf.sh is missing in the master. Its there in 2.0.4. So the wget in the readme gives a 404. 

Regards,

Marc

**Comment by bonnefoa** [comment]
Hi, 

I've updated the shell plugin instructions and README with the v3. 
There's no more `kubectl_fzf.sh` as it has been merged with the bash/zsh file to simplify installations. 
I'm still chasing bugs and updating readme but the v3 should approach a somewhat stable state now.
Happy to have feedbacks if you have any over issues or if things are working as expected!

Thanks,
Anthonin
