### ISSUE TITLE
FZF Config error on tab completion

### ISSUE THREAD

**Issue by dan-kez** [bonnefoa/kubectl-fzf#5]
Hello! Thanks for making this plugin - I'm very excited to use it!

I'm running into an issue where tab completion does does attempt to trigger fzf but it appears that there is a configuration error. I have included the output of a few commands below

```
k get pods invalid preview window layout: down:
invalid preview window layout: down:
invalid preview window layout: down:
```

```
k get nodes awk: syntax error at source line 1
 context is
         >>> {a[$5][ <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
join: malformed -o option field
invalid preview window layout: down:
awk: syntax error at source line 1
 context is
         >>> {a[$5][ <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
join: malformed -o option field
invalid preview window layout: down:
awk: syntax error at source line 1
 context is
         >>> {a[$5][ <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
join: malformed -o option field
invalid preview window layout: down:

```

I've installed using the following:
```
go get -u github.com/bonnefoa/kubectl-fzf/cmd/cache_builder
# If you update, you need to recompile cache_builder with
go install github.com/bonnefoa/kubectl-fzf/cmd/cache_builder
```
and 
```

# zsh version
echo "source <(kubectl completion zsh)" >> ~/.zshrc
echo "source $GOPATH/src/github.com/bonnefoa/kubectl-fzf/kubectl_fzf.sh" >> ~/.zshrc
```

I have run cache_builder successfully

Anythoughts/. I am on OSX.

**Comment by omrikiei** [comment]
Hi, also encountered it, issued a fix..

**Comment by bonnefoa** [comment]
What fzf version do you have? 
`--preview-window` option was introduced with fzf 0.13.0.
I'm running version 0.18.0

**Comment by omrikiei** [comment]
@bonnefoa I've experienced the same issue with fzf 0.18.0
I was able to resolve the `invalid preview window layout: down:` error by removing leading spaces from the wc command for counting Header columns(see [pull request](https://github.com/bonnefoa/kubectl-fzf/pull/8))
Regarding the other issue with awk, I think that osx uses nawk by default - which does not support the multidimensional arrays syntax as in gawk(`a[i][j]`)
this can be fixed either by installing gawk or refraining from this syntax.

**Comment by bonnefoa** [comment]
Both issues should be fixed on master now. 
Thanks for the report!
